align_method: auto
align_orientation_prior: vertical
bundle_outlier_filtering_type: AUTO
bundle_use_gcp: true
bundle_use_gps: false
feature_min_frames: 8000
feature_process_size: 2304
feature_type: HAHOG
flann_algorithm: KDTREE
local_bundle_radius: 0
matcher_type: WORDS
matching_gps_distance: 0
matching_gps_neighbors: 8
matching_graph_rounds: 50
optimize_camera_parameters: true
processes: 8
reconstruction_algorithm: incremental
retriangulation_ratio: 2
sift_peak_threshold: 0.066
triangulation_type: ROBUST
undistorted_image_format: tif
undistorted_image_max_size: 576
use_exif_size: false
